In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
a = tf.constant(2, dtype=np.int64)
b = tf.constant(5, dtype=np.int64)

In [3]:
op1 = tf.add(a,b)
op1

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [4]:
a+b # same as tf.add

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [5]:
v = a+b
u = v+2
w = v*u
z = w*3
z

<tf.Tensor: shape=(), dtype=int64, numpy=189>

In [6]:
np.add(3, 5)

8

In [9]:
def func(a,b):
        z = tf.multiply(a, b, name='z')
        y1 = tf.constant(3, name='3')
        y2 = tf.constant(4)
        w1 = tf.add(z, y1, name='w1')
        w2 = tf.add(z, y2, name='w2')
        
        return(w1+w2)

In [10]:
q = tf.Variable(10)
p = tf.Variable(15)

func(q, p)

<tf.Tensor: shape=(), dtype=int32, numpy=307>

In [13]:
@tf.function # to process the function using tensorflow algo
def func1(a,b):
    with tf.name_scope('first'): # first block
        z = tf.multiply(a, b, name='z')
    with tf.name_scope('second'): # second block
        y1 = tf.constant(3, name='3')
        y2 = tf.constant(4)
        w1 = tf.add(z, y1, name='w1')
        w2 = tf.add(z, y2, name='w2')
        
    return(w1+w2)

In [14]:
func1(10, 20)

<tf.Tensor: shape=(), dtype=int32, numpy=407>