In [1]:
import numpy as np

In [125]:
class Queue:
    
    def __init__(self):
        self.__end = -1
        self.__size = 0
        self.__data = np.zeros((10,), dtype= int)
        
    def isFull(self):
        return self.__size == len(self.__data)
    
    def isEmpty(self):
        return self.__size == 0
    
    def size(self):        
        return self.__size
    
    def add(self, value):
        if self.isFull():
            return "queue is full"
        
        else:
            self.__end += 1
            self.__data[self.__end] = value
            self.__size += 1
    
    
    def remove(self):
        if self.isEmpty():
            return "Queue is empty"
        
        else:
            remove = self.__data[0]
            for i in range(self.__end):
                self.__data[i] = self.__data[i + 1]
                
            self.__end -= 1
            self.__size -= 1
            return remove
                
    def __repr__(self):
        return str(self.__data[:self.__end+1])

In [3]:
q = Queue()

In [4]:
q.add(10)
q.add(11)
q.add(12)
q.add(20)

In [5]:
q.remove()

10

In [6]:
q

[11 12 20]

# Circular Queue

In [79]:
class CircularQueue:
    
    def __init__(self):
        self.__front = 0
        self.__end = 0
        self.__size = 0
        self.__data = np.zeros((10,), dtype = int)
        
    def isFull(self):
        return self.__size == len(self.__data)
    
    def isEmpty(self):
        return self.__size == 0
    
    def size(self):        
        return self.__size
    
    def add(self, value):
        
        if self.isFull():
            print("Queue is Full")
        
        else: 
            self.__data[self.__end] = value
            self.__end +=1
            self.__end = self.__end % len(self.__data)
            self.__size +=1

    def remove(self):
        if self.isEmpty():
            print("Queue is Empty")
            
        else:
            removed = self.__data[self.__front]
            self.__front +=1
            self.__front = self.__front % len(self.__data)
            self.__size -=1
            return removed
            
    def __repr__(self):
        if self.__size == 0:
            return '[]'
        elif self.__front < self.__end:
            cut = self.__data[self.__front:self.__end]
        else:
            cut1 = self.__data[self.__front:]
            cut2 = self.__data[:self.__end]
            cut =  np.concatenate((cut1, cut2))
            return f'[{", ".join(map(str, cut))}]'

In [80]:
cq = CircularQueue()

In [81]:
for i in range(10):
    cq.add(i+1)
    

In [82]:
cq

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [83]:
cq.remove()

1

In [84]:
cq

[2, 3, 4, 5, 6, 7, 8, 9, 10]

# Stack Using Queue

In [126]:
# add Effecient
class SUQ:
    
    def __init__(self):
        
        self.q1 = Queue()
        self.q2 = Queue()
        
    def add(self, value):
        self.q1.add(value)
        
    def pop(self):
        while self.q1.size() != 1 :
            self.q2.add(self.q1.remove())
        removed = self.q1.remove()
        self.q1, self.q2 = self.q2, self.q1
        return removed
    
    def dis(self):
        print(self.q1)

In [127]:
sq = SUQ()

for i in range(10):
    sq.add(i + 1)

sq.dis()

sq.pop()

[ 1  2  3  4  5  6  7  8  9 10]


10

In [128]:
sq.dis()

[1 2 3 4 5 6 7 8 9]


In [131]:
#Remove effecient
class SUQ:
    
    def __init__(self):
        
        self.q1 = CircularQueue()
        self.q2 = CircularQueue()
        
    def add(self, value):
        self.q2.add(value)
        while not self.q1.isEmpty() :
            self.q2.add(self.q1.remove())
        self.q1, self.q2 = self.q2, self.q1
        
        
    def pop(self):
        return self.q1.remove()
    def dis(self):
        print(self.q1)

In [132]:
sq = SUQ()

for i in range(10):
    sq.add(i + 1)

sq.dis()

sq.pop()

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


10