In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_regression

In [2]:
bias = 100
x, y = make_regression(n_features=4, bias=bias, noise=10, random_state=42)

In [3]:
class CustomCloseLinearReg:
    
    def fit(self, x, y):
        
        x = np.hstack([np.ones([x.shape[0], 1]), x])
        y = y.reshape(-1, 1)
        
        first = np.linalg.inv(np.dot(x.T, x))
        second = np.dot(x.T, y)
        
        self.theta_ = np.dot(first, second)
        
    def predict(self, x):
        
        x = np.hstack([np.ones([x.shape[0], 1]), x])
        
        return np.dot(x, self.theta_) 

In [4]:
model = CustomCloseLinearReg()

In [5]:
model.fit(x, y)

In [6]:
model.predict(x[:10])

array([[ 94.85255944],
       [ 50.34423332],
       [-30.07314717],
       [107.3453379 ],
       [-34.40987675],
       [143.55941103],
       [ 98.29972569],
       [ 67.75313807],
       [-58.48364998],
       [128.84465   ]])

In [7]:
y[:10]

array([ 91.42452817,  67.27652907, -21.41679852, 107.65226614,
       -33.47206507, 134.70114338,  89.51540077,  69.58301091,
       -64.36203085, 137.59692238])

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
m2 = LinearRegression()

In [10]:
m2.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
m2.predict(x[:10])

array([ 94.85255944,  50.34423332, -30.07314717, 107.3453379 ,
       -34.40987675, 143.55941103,  98.29972569,  67.75313807,
       -58.48364998, 128.84465   ])

In [12]:
from sklearn.datasets import load_boston

In [13]:
x, y = load_boston(return_X_y=True)

In [14]:
model.fit(x, y)

In [15]:
model.predict(x[:10])

array([[30.00384338],
       [25.02556238],
       [30.56759672],
       [28.60703649],
       [27.94352423],
       [25.25628446],
       [23.00180827],
       [19.53598843],
       [11.52363685],
       [18.92026211]])

In [16]:
y[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [17]:
m2.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
m2.predict(x[:10])

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211])

In [19]:
y[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])