In [1]:
import numpy as np

In [2]:
a = np.array([15, 5]).reshape(2, 1)

In [3]:
a

array([[15],
       [ 5]])

In [4]:
sum(a)

array([20])

In [5]:
b = np.arange(15).reshape(3, 5)

In [6]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
c = np.arange(5).reshape(5,)

In [8]:
c

array([0, 1, 2, 3, 4])

In [9]:
np.sum(b) # sum of all elements in b

105

In [10]:
np.add(b, c) # add elements acc to same index like 0,0

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [25]:
np.sum(b, axis=0) # add elements by axis 0

array([15, 18, 21, 24, 27])

In [12]:
np.min(b)

0

In [13]:
np.max(b)

14

In [14]:
b - c

array([[ 0,  0,  0,  0,  0],
       [ 5,  5,  5,  5,  5],
       [10, 10, 10, 10, 10]])

In [15]:
b + c

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [16]:
b * c

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56]])

In [17]:
b ** c

array([[    1,     1,     4,    27,   256],
       [    1,     6,    49,   512,  6561],
       [    1,    11,   144,  2197, 38416]])

In [18]:
b < 10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [19]:
b > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [23]:
np.argmax(c) # index of bigest element

4

In [24]:
np.argmin(c) # index of smallest element

0

In [27]:
np.sin(c) # sine of array c

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.ones